# Site wide configuration

title: Mahango
locale: en_GB
description: Web development.
logo: mahango.png
search: false
url: http://mahango.com # http://mahango.github.io # http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Mahango
  avatar: mahango.png
  email: info@mahango.com
  disqus-shortname:
  twitter: #mahango
  facebook: #mahango
  github: mahango
  stackexchange: #http://stackoverflow.com/users/505107/mahango
  linkedin: #mahango
  instagram: #mahango
  flickr: #mahango
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #mahango
    analytics: UA-295927-11
    verify:
    ad-client:
    ad-slot:
  bing-verify:
